version: '3.8'
services: 
    web:
        build: .
        working_dir: /app
        command: >
            sh -c "composer update --no-scripts &&
            php artisan swapi:install &&
            php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db   
    db:
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: swapi
            MYSQL_USER: admin
            MYSQL_ROOT: root
            MYSQL_PASSWORD: toor
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1